name: CD-docker-pusher

on:
  workflow_run:
    workflows: [ "Release" ]
    types: [ completed ]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Push docker to Docker Hub
    steps:
      - uses: actions/checkout@master
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build docker
        run: docker build . -t wnubbles/telegram-bot
      - name: Push docker
        run: docker push wnubbles/telegram-bot
