name: CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Lint and test all py-files
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ../../requirements.txt
    - name: Analysing the code with flake8
      run: |
        flake8 `ls -R|grep .py$|xargs`
    - name: Testing the code with pytest
      run: |
        python -m pytest .

  build_docker:
    runs-on: ubuntu-latest
    name: Check the dockerfile
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)


