name: Release

on:
  release:
    types: [created]
  tags:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Extra test all py-files
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Testing the code with pytest
      run: |
        python -m pytest .